# Generated by Django 4.2.4 on 2023-09-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telegram_name',
        ),
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.PositiveIntegerField(default=1, verbose_name='идентификатор чата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='username'),
        ),
    ]
