# Generated by Django 4.2.4 on 2023-09-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_remove_user_telegram_name_user_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.CharField(blank=True, choices=[('LASER', 'Лазерный участок'), ('WELDING', 'Сварочный участок'), ('MOTOR', 'Моторный участок'), ('ELECTRICIAN', 'Участок электрики'), ('ASSEMBLY', 'Сборочный участок')], max_length=11, null=True, verbose_name='место работы'),
        ),
    ]
