# Generated by Django 4.2.4 on 2023-09-10 09:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_user_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'сотрудник', 'verbose_name_plural': 'сотрудники'},
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата и время')),
                ('item_number', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(limit_value=11)], verbose_name='номенклатурный номер')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='количество')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
                ('sender', models.CharField(choices=[('LASER', 'Лазерный участок'), ('WELDING', 'Сварочный участок'), ('MOTOR', 'Моторный участок'), ('ELECTRICIAN', 'Участок электрики'), ('ASSEMBLY', 'Сборочный участок')], max_length=11, verbose_name='отправитель')),
                ('receiver', models.CharField(choices=[('LASER', 'Лазерный участок'), ('WELDING', 'Сварочный участок'), ('MOTOR', 'Моторный участок'), ('ELECTRICIAN', 'Участок электрики'), ('ASSEMBLY', 'Сборочный участок')], max_length=11, verbose_name='получатель')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='productions', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'факт производства',
                'verbose_name_plural': 'факты производства',
            },
        ),
    ]
