# Generated by Django 4.2.4 on 2023-09-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_alter_user_options_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_id',
            field=models.PositiveIntegerField(null=True, verbose_name='идентификатор чата'),
        ),
    ]
