# Generated by Django 4.2.4 on 2023-09-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_alter_user_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='production',
            name='sender',
        ),
        migrations.AddField(
            model_name='production',
            name='location',
            field=models.CharField(choices=[('LASER', 'Лазерный участок'), ('WELDING', 'Сварочный участок'), ('MOTOR', 'Моторный участок'), ('ELECTRICIAN', 'Участок электрики'), ('ASSEMBLY', 'Сборочный участок')], default='LASER', max_length=11, verbose_name='цех производства'),
            preserve_default=False,
        ),
    ]
