# Generated by Django 4.2.4 on 2023-09-21 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemNumber',
            fields=[
                ('name', models.TextField(verbose_name='наименование номенклатуры')),
                ('number', models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(limit_value=11)], verbose_name='номер')),
            ],
            options={
                'verbose_name': 'номенклатурный номер',
                'verbose_name_plural': 'номенклатурные номера',
            },
        ),
    ]
